version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGHLDS3003Project
  gitServerName: srcGithubCtrl_Arti_bearer
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
